#!/bin/bash

# Screenshot Capture Guide for Capstone Project Report
# This script helps you capture screenshots systematically

echo "========================================"
echo "SCREENSHOT CAPTURE GUIDE"
echo "========================================"
echo ""
echo "Follow these steps to capture screenshots for your report:"
echo ""

echo "1. ENCRYPTION DEMO SCREENSHOTS:"
echo "   Run: cd encryption && ./demo_encryption.sh"
echo "   Capture screenshots of:"
echo "   - Original file content"
echo "   - Encryption process output"
echo "   - Decryption process output"
echo "   - 'SUCCESS: Files match!' verification"
echo ""

echo "2. HASHING DEMO SCREENSHOTS:"
echo "   Run: cd ../hashing && ./demo_hashing.sh"
echo "   Capture screenshots of:"
echo "   - Original file hash generation"
echo "   - Modified file hash generation"
echo "   - 'Hashes are different - tampering detected!' message"
echo ""

echo "3. PUBLIC KEY DEMO SCREENSHOTS:"
echo "   Run: cd ../public-key && ./demo_public_key.sh"
echo "   Capture screenshots of:"
echo "   - Key generation output"
echo "   - Key listing (gpg --list-keys)"
echo "   - Encryption success message"
echo "   - Decryption output"
echo "   - Signature verification ('Good signature')"
echo ""

echo "4. SECURE EMAIL DEMO SCREENSHOTS:"
echo "   Run: cd ../scenario && ./demo_secure_email.sh"
echo "   Capture screenshots of:"
echo "   - Key generation for Alice and Bob"
echo "   - Alice's encrypted message creation"
echo "   - Bob's decryption and reply"
echo "   - Alice's receipt of encrypted reply"
echo ""

echo "========================================"
echo "TIPS FOR CAPTURING SCREENSHOTS:"
echo "========================================"
echo "- Use clear, high-resolution captures"
echo "- Include terminal prompts for context"
echo "- Capture the complete output of each command"
echo "- Save as PNG format for best quality"
echo "- Name files descriptively (e.g., 'encryption_demo.png')"
echo ""

echo "========================================"
echo "QUICK TEST RUN:"
echo "========================================"
echo "To test all demos quickly, run the master script:"
echo "bash run_all_demos.sh"
echo ""
echo "This will show all outputs sequentially for screenshot capture."